version: "3.6"

services:
  db:
    image: mongo:6.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./server/data/db:/data/db
      - ./server/configs/mongoDb:/data/configdb
    ports:
      - 27017:27017

  server:
    build: ./docker
    command: sh /entrypoint.sh && /wait-for-it.sh db:27017 -t 300
    volumes:
      - ./server:/app
      - ./server/node_modules:/app/node_modules
    depends_on:
      - db
    ports:
      - 3000:3000

  web:
    build: ./docker
    command: sh /entrypoint.sh
    volumes:
      - ./web:/app
    ports:
      - 5000:3000
