version: "3.6"

services:
  # https://hub.docker.com/_/mongo
  db:
    image: mongo:latest
    restart: on-failure:5
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
      - mongoConfig:/data/configdb

  mongo-express:
    image: mongo-express:latest
    restart: on-failure:5
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: db
    depends_on:
      - db

volumes:
  data:
  mongoConfig:



  # server:
  #   tty: true
  #   stdin_open: true
  #   build: ./docker/server
  #   command: sh /docker-entrypoint.sh
  #   volumes:
  #     - ./server:/app
  #     - '/app/node_modules'
  #   depends_on:
  #     - db
  #     - mongo-express
  #     - redis

  # web:
  #   tty: true
  #   stdin_open: true
  #   build: ./docker/web
  #   command: sh /docker-entrypoint.sh
  #   volumes:
  #     - ./web:/app
  #     - '/app/node_modules'
  #   depends_on:
  #     - server

  # nginx:
  #   image: nginx
  #   depends_on:
  #     - web
  #   volumes:
  #     - ./docker/nginx/dev.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - 3000:3000

  # redis:
  #   image: redis

  # sidekiq:
  #   <<: *web_base
  #   command: sh /docker-entrypoint-sidekiq.sh
  #   ports: []

  # mailhog:
  #   image: mailhog/mailhog
  #   ports:
  #     - 8025:8025


