version: "3.6"

services:
  db:
    image: mongo:6.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./server/data/db:/data/db
      - ./server/configs/mongoDb:/data/configdb

  server:
    tty: true # Don't understand
    stdin_open: true # Don't understand
    build: ./docker/server
    command: sh /entrypoint.sh && /wait-for-it.sh db:27017 -t 300
    volumes:
      - ./server:/app
      - ./server/node_modules:/app/node_modules
    # depends_on:
    #   - db
    ports:
      - 3000:3000

  # web:
  #   tty: true
  #   stdin_open: true
  #   build: ./
  #   command: npm start
  #   volumes:
  #     - ./web:/app
  #     - './web/node_modules:/app/node_modules'
  #   depends_on:
  #     - server
  #   ports:
  #     - 5000:3000
